name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0, 1.0.0-beta.1)'
        required: true
        type: string
      tag:
        description: 'NPM dist-tag (latest, beta, next)'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta
          - next
          - alpha

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run full test suite
        run: npm run test:ci
      
      - name: Build package
        run: npm run build
      
      - name: Test local installation
        run: |
          npm pack
          package_file=$(ls @termstyle-core-*.tgz)
          echo "Testing package: $package_file"
          
          cd /tmp
          npm init -y
          npm install $GITHUB_WORKSPACE/$package_file
          
          # Test CommonJS
          node -e "const ts = require('@termstyle/core'); console.log(ts.green('CommonJS import successful!'))"
          
          # Test ESM
          echo '{"type": "module"}' > package.json
          node -e "import ts from '@termstyle/core'; console.log(ts.blue('ESM import successful!'))"
      
      - name: Publish to NPM
        run: npm publish --tag ${{ github.event.inputs.tag || 'latest' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Verify publication
        run: |
          sleep 10
          npm view @termstyle/core